server:
  port: 10001
spring:
  application:
    name: GOODSSERVER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qg_goods_db
    username: root
    password: ok
  redis:
    database: 0
    password: ok
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual  #消费端手工ack的配置
        concurrency: 1
        max-concurrency: 5
#  activemq:
#    broker-url: tcp://192.168.1.110:61616?jms.optimizeAcknowledge=true&jms.optimizeAcknowledgeTimeOut=30000&jms.redeliveryPolicy.maximumRedeliveries=10
#    user: admin
#    password: admin
#  jms:
#    pub-sub-domain: false
#  kafka:
#    bootstrap-servers: 192.168.1.110:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml