server:
  port: 8001
spring:
  application:
    name: USERSERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_user
    username: root
    password: ok
  redis:
    database: 0
    password: ok
    host: localhost
    port: 6379
#  kafka:
#    bootstrap-servers: 192.168.1.110:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml